import {Lead} from '../models/leads/lead';

export const NEWLEAD: Lead = {
    id: -1,
    isActive: false,
    createdOn: '',
    createdBy: null,
    modifiedOn: '',
    modifiedBy: null,
    title: '',
    firstName: '',
    lastName: '',
    primaryPhone: '',
    mobilePhone: '',
    fax: '',
    image: '',
    skypeId: '',
    twitter: '',
    linkedIn: '',
    primaryEmail: '',
    secondaryEmail: '',
    email_opt_out: false,
    address: null,
    company: null,
    notes: [],
    activities: [],
    source: '',
    owner: null,
    description: '',
    lead_status: ''
};
export const LEADS: Lead[] = [
    {
        id: 1,
        isActive: true,
        createdOn: '',
        createdBy: null,
        modifiedOn: '',
        modifiedBy: null,
        title: '',
        firstName: 'Joshua',
        lastName: 'Szuslik',
        primaryPhone: '4142023939',
        mobilePhone: '4149419014',
        fax: '',
        image: 'https://media.licdn.com/mpr/mpr/shrinknp_400_400/p/4/005/046/32f/3b07c21.jpg',
        skypeId: '',
        twitter: '',
        linkedIn: '',
        primaryEmail: 'joshua.szuslik@omniresources.com',
        secondaryEmail: '',
        email_opt_out: false,
        address: null,
        company: null,
        notes: [],
        activities: [],
        source: 'Website',
        owner: null,
        description: '',
        lead_status: ''
    },
    {
        id: 2,
        isActive: true,
        createdOn: '',
        createdBy: null,
        modifiedOn: '',
        modifiedBy: null,
        title: '',
        firstName: 'Max',
        lastName: 'McCoy',
        primaryPhone: '4145556666',
        mobilePhone: '4148889999',
        fax: '',
        image: 'https://lanex.com/wp-content/uploads/2017/08/max-mccoy-e1502315349156.jpg',
        skypeId: '',
        twitter: '',
        linkedIn: '',
        primaryEmail: 'max@lanex.com',
        secondaryEmail: '',
        email_opt_out: false,
        address: null,
        company: null,
        notes: [],
        activities: [],
        source: 'Website',
        owner: null,
        description: '',
        lead_status: ''
    }
];
