import {Lead} from '../models/leads/lead';
import {NEWUSER} from './mockusers';
import {NEWADDRESS} from './mockaddresses';
import {NEWACCOUNT} from './mockaccounts';

export const NEWLEAD: Lead = {
    id: -1,
    isActive: false,
    createdOn: '',
    createdBy: null,
    modifiedOn: '',
    modifiedBy: null,
    title: '',
    firstName: '',
    lastName: '',
    primaryPhone: '',
    mobilePhone: '',
    fax: '',
    image: '',
    skypeId: '',
    twitter: '',
    linkedIn: '',
    primaryEmail: '',
    secondaryEmail: '',
    email_opt_out: false,
    address: null,
    company: null,
    notes: [],
    activities: [],
    source: '',
    owner: null,
    description: '',
    lead_status: ''
};
export const LEADS: Lead[] = [
    {
        id: 1,
        isActive: true,
        createdOn: '10-11-17',
        createdBy: {
            id: 1,
            isActive: true,
            createdOn: '',
            createdBy: null,
            modifiedOn: '',
            modifiedBy: null,
            username: 'jszuslik',
            password: '',
            email: 'joshuaszuslik@gmail.com',
            firstName: 'Joshua',
            lastName: 'Szuslik',
            phone: '41420203939',
            role: 'admin'
        },
        modifiedOn: '10-11-17',
        modifiedBy: {
            id: 1,
            isActive: true,
            createdOn: '',
            createdBy: null,
            modifiedOn: '',
            modifiedBy: null,
            username: 'jszuslik',
            password: '',
            email: 'joshuaszuslik@gmail.com',
            firstName: 'Joshua',
            lastName: 'Szuslik',
            phone: '41420203939',
            role: 'admin'
        },
        title: 'Mr.',
        firstName: 'Joshua',
        lastName: 'Szuslik',
        primaryPhone: '4142023939',
        mobilePhone: '4149419014',
        fax: '',
        image: 'https://media.licdn.com/mpr/mpr/shrinknp_400_400/p/4/005/046/32f/3b07c21.jpg',
        skypeId: 'joshua.szuslik',
        twitter: 'JoshuaSzuslik',
        linkedIn: 'https://www.linkedin.com/jszuslik',
        primaryEmail: 'joshua.szuslik@omniresources.com',
        secondaryEmail: 'jszuslik@gmail.com',
        email_opt_out: false,
        address: {
            id: 1,
            isActive: true,
            address1: 'W257S6750 Fox Ct',
            address2: '',
            city: 'Waukesha',
            state: 'WI',
            zip: '53189',
            country: 'United States'
        },
        company: {
            id: 1,
            isActive: true,
            createdOn: '10-11-17',
            createdBy: {
                id: 1,
                isActive: true,
                createdOn: '',
                createdBy: null,
                modifiedOn: '',
                modifiedBy: null,
                username: 'jszuslik',
                password: '',
                email: 'joshuaszuslik@gmail.com',
                firstName: 'Joshua',
                lastName: 'Szuslik',
                phone: '41420203939',
                role: 'admin'
            },
            modifiedOn: '10-11-17',
            modifiedBy: {
                id: 1,
                isActive: true,
                createdOn: '',
                createdBy: null,
                modifiedOn: '',
                modifiedBy: null,
                username: 'jszuslik',
                password: '',
                email: 'joshuaszuslik@gmail.com',
                firstName: 'Joshua',
                lastName: 'Szuslik',
                phone: '41420203939',
                role: 'admin'
            },
            accountOwner: {
                id: 1,
                isActive: true,
                createdOn: '',
                createdBy: null,
                modifiedOn: '',
                modifiedBy: null,
                username: 'jszuslik',
                password: '',
                email: 'joshuaszuslik@gmail.com',
                firstName: 'Joshua',
                lastName: 'Szuslik',
                phone: '41420203939',
                role: 'admin'
            },
            name: 'Omni Resources',
            industry: 'Tech',
            employees: '150-200',
            annualRevenue: '$10,000,000',
            phone: '4142023939',
            website: 'https://www.omniresources.com',
            rating: 5,
            fax: '',
            ticker: 'OMNI',
            ownership: 'ESOP',
            locations: [
                {
                    id: 1,
                    isActive: true,
                    address1: 'W257S6750 Fox Ct',
                    address2: '',
                    city: 'Waukesha',
                    state: 'WI',
                    zip: '53189',
                    country: 'United States'
                }
            ]
        },
        notes: [],
        activities: [],
        source: 'Website',
        owner: {
            id: 1,
            isActive: true,
            createdOn: '',
            createdBy: null,
            modifiedOn: '',
            modifiedBy: null,
            username: 'jszuslik',
            password: '',
            email: 'joshuaszuslik@gmail.com',
            firstName: 'Joshua',
            lastName: 'Szuslik',
            phone: '41420203939',
            role: 'admin'
        },
        description: '',
        lead_status: 'Active'
    },
    {
        id: 2,
        isActive: true,
        createdOn: '',
        createdBy: NEWUSER,
        modifiedOn: '',
        modifiedBy: NEWUSER,
        title: '',
        firstName: 'Max',
        lastName: 'McCoy',
        primaryPhone: '4145556666',
        mobilePhone: '4148889999',
        fax: '',
        image: 'https://lanex.com/wp-content/uploads/2017/08/max-mccoy-e1502315349156.jpg',
        skypeId: '',
        twitter: '',
        linkedIn: '',
        primaryEmail: 'max@lanex.com',
        secondaryEmail: '',
        email_opt_out: false,
        address: NEWADDRESS,
        company: NEWACCOUNT,
        notes: [],
        activities: [],
        source: 'Website',
        owner: NEWUSER,
        description: '',
        lead_status: ''
    }
];
